apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "700VF",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["vfio-pci"]
                }
            }, {
                "resourceName": "700PF",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["1572"],
                    "drivers": ["vfio-pci"]
                }
            }
        ]
    }

